version: "3.9"

services:
  web:
    build: .
    env_file:
      - .env.docker
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    # environment:
    #   - REDIS_HOST=redis
    #   - REDIS_PORT=6379
    #   - REDIS_USERNAME=default
    #   - REDIS_PASS=yourpass
    #   - REDIS_DB_NAME=0
    depends_on:
      - redis
      - mongo

  worker:
    build: .
    env_file:
      - .env.docker
    command: celery -A app.tasks.worker.celery_app worker --loglevel=info -P solo
    volumes:
      - .:/app
    # environment:
    #   - REDIS_HOST=redis
    #   - REDIS_PORT=6379
    #   - REDIS_USERNAME=default
    #   - REDIS_PASS=yourpass
    #   - REDIS_DB_NAME=0
    depends_on:
      - redis
      - mongo

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
